In [1]:
# Cek versi library
import sys
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt

print("Python      :", sys.version.split()[0])
print("pandas      :", pd.__version__)
print("numpy       :", np.__version__)
print("matplotlib  :", matplotlib.__version__)

Python      : 3.11.16
pandas      : 2.2.3
numpy       : 1.26.4
matplotlib  : 3.8.4

In [2]:
# Tipe data dasar di Python
nama_mahasiswa = "Hans"         # string (teks)
npm = 2505060077              # integer (bilangan bulat)
ipk = 3.75                      # float (bilangan desimal)
aktif_kuliah = True             # boolean (benar/salah)

print(f"Nama       : {nama_mahasiswa} ({type(nama_mahasiswa).__name__})")
print(f"NPM        : {npm} ({type(npm).__name__})")
print(f"IPK        : {ipk} ({type(ipk).__name__})")
print(f"Aktif      : {aktif_kuliah} ({type(aktif_kuliah).__name__})")

Nama       : Hans (str)
NPM        : 2505060077 (int)
IPK        : 3.75 (float)
Aktif      : True (bool)

In [3]:
daftar_nilai = [85, 90, 78, 92, 88]   # list: kumpulan nilai terurut
print("Daftar nilai:", daftar_nilai)
print("Rata-rata   :", sum(daftar_nilai) / len(daftar_nilai))

mahasiswa = {                          # dictionary: pasangan key-value
    "nama": "Budi",
    "npm": 210411001,
    "jurusan": "Teknologi Informasi",
    "semester": 3
}
print("\nData mahasiswa:")
for key, value in mahasiswa.items():
    print(f"  {key}: {value}")

Daftar nilai: [85, 90, 78, 92, 88]
Rata-rata   : 86.6

Data mahasiswa:
  nama: Budi
  npm: 210411001
  jurusan: Teknologi Informasi
  semester: 3

In [4]:
# Membuat DataFrame dari dictionary
# Studi kasus: data penjualan mingguan sebuah UMKM di beberapa kota

data_penjualan = {
    "kota": ["Magelang", "Yogyakarta", "Semarang", "Solo", "Magelang", "Yogyakarta", "Semarang", "Solo"],
    "minggu": [1, 1, 1, 1, 2, 2, 2, 2],
    "produk": ["Kaos", "Kaos", "Kaos", "Kaos", "Kaos", "Kaos", "Kaos", "Kaos"],
    "unit_terjual": [120, 95, 150, 80, 135, 110, 160, 90],
    "harga_satuan": [75000, 75000, 75000, 75000, 75000, 75000, 75000, 75000]
}

df = pd.DataFrame(data_penjualan)
df

         kota  minggu produk  unit_terjual  harga_satuan
0    Magelang       1   Kaos           120         75000
1  Yogyakarta       1   Kaos            95         75000
2    Semarang       1   Kaos           150         75000
3        Solo       1   Kaos            80         75000
4    Magelang       2   Kaos           135         75000
5  Yogyakarta       2   Kaos           110         75000
6    Semarang       2   Kaos           160         75000
7        Solo       2   Kaos            90         75000

In [7]:
import pandas as pd

# Soal 1
data = {
    'nama': ['Hans', 'Firefly', 'Castorice', 'Hoth', 'Lucia'],
    'uts': [75, 85, 90, 65, 88],
    'uas': [80, 90, 85, 70, 95]
}

# 2. Buat DataFrame df_nilai
df_nilai = pd.DataFrame(data)

# 3. Hitung kolom nilai_akhir
df_nilai['nilai_akhir'] = (df_nilai['uts'] * 0.4) + (df_nilai['uas'] * 0.6)

# Tampilkan tabel
df_nilai

        nama  uts  uas  nilai_akhir
0       Hans   75   80         78.0
1    Firefly   85   90         88.0
2  Castorice   90   85         87.0
3       Hoth   65   70         68.0
4      Lucia   88   95         92.2

In [8]:
# Soal 2
df_nilai[df_nilai['nilai_akhir'] > 80]

        nama  uts  uas  nilai_akhir
1    Firefly   85   90         88.0
2  Castorice   90   85         87.0
4      Lucia   88   95         92.2